src/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
                    login_views,
                    register_user,
                    guest_login_views
                )

app_name = "accounts"
urlpatterns = [
    path('login/', login_views,name="login"),
    path('guest-login/', guest_login_views,name="guest-login"),
    path('logout/', LogoutView.as_view(),name="logout"),
    path('register/', register_user,name="register"),
]

src/address/urls.py
from django.urls import path
from .views import (
            checkout_address_create_view,
            checkout_address_reuse_view
        )

app_name = "address"

urlpatterns = [
    path('', checkout_address_create_view,name="addresses"),
    path('select-address/', checkout_address_reuse_view,name="address_reuse"),
    
]

src/cart/urls.py
from django.urls import path
from  .views import (
                    cart_home,
                    cart_update,
                    checkout_home,
                    checkout_done,
                    cart_update_api_view
                )

app_name = "cart"

urlpatterns = [
    path('', cart_home,name="cart-home"),
    path('update/', cart_update,name="cart-update"),
    path('checkout/', checkout_home,name="checkout"),
    path('checkout/success/', checkout_done,name="checkout-success"),
    path('api/', cart_update_api_view,name="cart-update-api"),
]

src/eCommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include("products.urls")),
    path('search/', include("search.urls")),
    path('cart/', include("cart.urls")),
    path('accounts/', include("accounts.urls")),
    path('address/', include("address.urls")),
    path('billing/', include("billing.urls")),
    path('', include("home.urls")),

]


if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/home/urls.py
from django.urls import path
from .views import (
                home_page
            )


app_name = "home"
urlpatterns = [

    path('',home_page,name="homepage")

]

src/cart/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import m2m_changed,pre_save 
from products.models import Product 
User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):

    def create_or_get(self,request):
        cart_id = request.session.get("cart_id",None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            cart_obj = qs.first()
            new_obj = False
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user 
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session["cart_id"] = cart_obj.id
        return cart_obj,new_obj


    def new(self,user=None):
        user_obj = None
        if user.is_authenticated:
            user_obj = user
        return self.get_queryset().create(user=user_obj)



class Cart(models.Model):
    user            = models.ForeignKey(User,blank=True,null=True,on_delete=models.CASCADE)
    product         = models.ManyToManyField(Product,blank=True)
    sub_total       = models.DecimalField(decimal_places=2,max_digits=100,default=0.00)
    total           = models.DecimalField(decimal_places=2,max_digits=100,default=0.00)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    objects = CartManager()


    def __str__(self):
        return str(self.id)

def cart_m2m_changed_reciever(sender,instance,action,*args,**kwargs):
    if action == "post_add" or action == "post_remove" or action == "post_clear":
        products = instance.product.all()
        total = 0
        for x in products:
            total += x.price
        if instance.sub_total != total:
            instance.sub_total = total
            instance.save()  

m2m_changed.connect(cart_m2m_changed_reciever, sender=Cart.product.through)

def cart_pre_save_receiver(sender,instance,*args,**kwargs):
    if instance.sub_total > 0:
        instance.total = Decimal(instance.sub_total) * Decimal(1.08)
    else:
        instance.total = 0.00

pre_save.connect(cart_pre_save_receiver,sender=Cart)

src/home/models.py
from django.db import models

# Create your models here.

src/cart/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,JsonResponse
from django.urls import reverse
from django.utils.http import is_safe_url 
from products.models import Product,ProductCategory
from billing.models import BillingProfile
from orders.models import Orders
from accounts.forms import (
                            LoginForm,
                            Register,
                            GuestForm
                        )
from accounts.models import GuestEmail
from address.models import Addresses
from address.forms import AddressForm
from .models import Cart 



def cart_update_api_view(request):
    cart_obj,new_obj = Cart.objects.create_or_get(request)
    product = [{"id":x.id,
                "url":x.get_absolute_url,
                "title":x.title,
                "price":x.price
            } for x in cart_obj.product.all()]
    cart_data = {
                "product":product,
                "sub_total":cart_obj.sub_total,
                "total":cart_obj.total
            }
    return JsonResponse(cart_data)


def cart_home(request):
    template_name = "cart/home.html"
    all_category = ProductCategory.objects.all()
    cart_obj,new_obj = Cart.objects.create_or_get(request)
    context = {
        "cart_obj":cart_obj,
        "all_category":all_category
    }
    return render(request,template_name,context)


def cart_update(request):
    product_id = request.POST.get("product_id")
    in_detail = request.POST.get("in_detail")

    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            return redirect("cart:cart-home")

        cart_obj,new_obj = Cart.objects.create_or_get(request)
        if product_obj in cart_obj.product.all():
            cart_obj.product.remove(product_obj)
            added = False
        else:
            cart_obj.product.add(product_obj)
            added = True
        request.session["cart_total"] = cart_obj.product.count()

        if request.is_ajax():
            json_data = {
                "added":added,
                "removed": not added,
                "cart_item_count":cart_obj.product.count()

            }
            return JsonResponse(json_data)

    return redirect("cart:cart-home")
 


def checkout_home(request):
    template_name = "cart/checkout.html"
    order_obj = None
   
    cart_obj,cart_created = Cart.objects.create_or_get(request)
    all_category = ProductCategory.objects.all()
    
    if cart_created or cart_obj.product.count() == 0:
        return redirect("cart:cart-home")

    login_form = LoginForm(request.POST or None)
    guest_form = GuestForm(request.POST or None)
    address_form = AddressForm(request.POST or None)
    billing_address_id = request.session.get("billing_address_id",None)
    shipping_address_id = request.session.get("shipping_address_id",None)
    billingprofile,billingprofile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None

    if billingprofile is not None:
        if request.user.is_authenticated:
            address_qs = Addresses.objects.filter(billing_profile=billingprofile)

        order_obj,order_obj_created = Orders.objects.new_or_get(billingprofile,cart_obj)
        
        if shipping_address_id:
            order_obj.shipping_address = Addresses.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address_id = Addresses.objects.get(id=billing_address_id)
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        is_done = order_obj.check_done()
        if is_done:
            did_charge,mgs = billingprofile.charge(order_obj)
            if did_charge:
                order_obj.mark_paid()
                request.session["cart_total"] = 0
                del request.session["cart_id"]
                if not billingprofile.user:
                    billingprofile.set_card_inactive()
                return redirect("cart:checkout-success")
            else:
                return redirect("cart:checkout")

    context = {
        "order_obj":order_obj,
        "billingprofile":billingprofile,
        "login_form":login_form,
        "guest_form" : guest_form,
        "address_form":address_form,
        "address_qs":address_qs,
        "all_category":all_category
    }

    return render(request,template_name,context)


def checkout_done(request):
    all_category = ProductCategory.objects.all()
    return render(request,"cart/checkout-done.html",{"all_category":all_category})

src/home/views.py
from django.shortcuts import render
from products.models import (
                        Product,
                        ProductCategory
                    )
from cart.models import Cart

def home_page(request):

    # get latest arival product
    new_products = Product.objects.latest_arival()

    # get featured product 
    featured_product = Product.objects.featured()

    # get mens collections
    mens_collection = Product.objects.mens_collection()

    # get mens collections
    womens_collection = Product.objects.womens_collection()

    # get offer
    special_offer = Product.objects.special_offer()

    # get special deal
    special_deal = Product.objects.special_deal()

    # get cart object
    cart_obj,new_obj = Cart.objects.create_or_get(request)

    # get category
    category = ProductCategory.objects.all()


    template_name = "home/index.html"
    
    context = {
        "new_products":new_products,
        "featured_product":featured_product,
        "cart_obj":cart_obj,
        "mens_collection":mens_collection,
        "special_offer":special_offer,
        "womens_collection":womens_collection,
        "special_deal":special_deal,
        "all_category":category,
        "category_count":category.count()
    }

    return render(request,template_name,context)

src/templates/cart/checkout-done.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Checkout | E-BUY</title>
	{% include "home/header.html" %}
</head>

<body>

	{% include "home/nav-others.html" %}
	<!-- //navigation -->
	<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<!-- page -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="{% url "home:homepage" %}">Home</a>
						<i>|</i>
					</li>
					<li>Checkout</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- //page -->
	<!-- checkout page -->
	<div class="privacy">
		<div class="container">
			<!-- tittle heading -->
			<h3 class="tittle-w3l">Success
				<span class="heading-style">
					<i></i>
					<i></i>
					<i></i>
				</span>
            </h3>
            
			<!-- //tittle heading -->
			<div class="checkout-right">
                <h4>Thanks for payment.Check your mail for invoice & Order detail</h4>
            </div>
		</div>
    </div>
    
	{% include "home/before-footer.html" %}	
	{% include "home/footer.html" %}	
  
</html>

src/templates/cart/checkout.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Checkout | E-BUY</title>
	{% include "home/header.html" %}
</head>

<body>

	{% include "home/nav-others.html" %}
	<!-- //navigation -->
	<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<!-- page -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="{% url "home:homepage" %}">Home</a>
						<i>|</i>
					</li>
					<li>Checkout</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- //page -->
	<!-- checkout page -->
	<div class="privacy">
		<div class="container">
			<!-- tittle heading -->
			<h3 class="tittle-w3l">Checkout
				<span class="heading-style">
					<i></i>
					<i></i>
					<i></i>
				</span>
            </h3>
            
			<!-- //tittle heading -->
			<div class="checkout-right">

                    {% if not billingprofile %}
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <p class="lead">Login</p>
                                {% include "accounts/snippets/form.html" with form=login_form next_url=request.build_absolute_uri %}
                            </div>
                            <div class="col-12 col-md-6">
                                <p class="lead">Continue as Guest</p>
                                {% url "accounts:guest-login" as guest_login %}
                                {% include "accounts/snippets/form.html" with form=guest_form next_url=request.build_absolute_uri action_url=guest_login %}
                            </div>
                        </div>
                    {% else %}
                    {% if not order_obj.shipping_address %}
                    <div class="row">
                        <div class="col-sm-8">
                            <p class="lead">Shipping Address</p>
                            {% url "address:addresses" as checkout_address_create %}
                            {% include "address/form.html" with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type="shipping" %}
                        </div>

                        <div class="col-sm-4">
                            <p class="lead">You can also select address</p>
                            {% url "address:address_reuse" as address_reuse %}
                            {% include "address/previous_address.html" with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=address_reuse %}
                        </div>
                    </div>
          
                    {% elif not order_obj.billing_address %}

                    <div class="row">
                        <div class="col-sm-8">
                            <p class="lead">Billing Address</p>
                            {% url "address:addresses" as checkout_address_create %}
                            {% include "address/form.html" with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type="billing" %}
                        </div>
    
                        <div class="col-sm-4">
                            <p class="lead">You can also select address</p>
                            {% url "address:address_reuse" as address_reuse%}
                            {% include "address/previous_address.html" with address_qs=address_qs next_url=request.build_absolute_uri action_url=address_reuse address_type='billing'%}
                        </div>
                    </div>
                    {% else %}

                    {% if not billingprofile.has_cards %}
                    <!-- enter credit card here -->

                    <p class="lead">Add a Payment Method</p>
                    <div class="row">
                        <div class="col-md-8">
                            <form class="payment-form" data-next-url="/cart/checkout/" method="POST" id="payment-form" data-token="pk_test_NW2dTXyWJD6CrGWqRLRmmZvA">
                                <div class="form-row">
                                    <div id="card-element" class="form-control">
                                    <!-- A Stripe Element will be inserted here. -->
                                    </div>
                                    <!-- Used to display form errors. -->
                                    <div id="card-errors" role="alert"></div>
                                </div>
                                <br>
                                <button class="btn btn-success">Submit Payment</button>
                            </form> 
                        </div>
                    </div>
                    {% else %}

                    <div class="table-responsive">
                        <table class="table table-bordered cart-table">
                            <tbody class = "cart-body">
                                <tr>
                                    <th>Cart Itmes</th>
                                    <td>
                                        {% for product in order_obj.cart.product.all %} {{ product }} {% if not forloop.last %},{% endif %} {% endfor %}
                                    </td>
                                </tr>
                                <tr>
                                    <th>Shipping Address</th>
                                    <td>
                                        {{ order_obj.shipping_address.address_line_1 }},
                                        {{ order_obj.shipping_address.address_line_2 }},
                                        {{ order_obj.shipping_address.city }},
                                        {{ order_obj.shipping_address.state }},
                                        {{ order_obj.shipping_address.country }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>Cart Total</th>
                                    <td>$ {{ order_obj.cart.total }}</td>
                                </tr>
                                <tr>
                                    <th>Shipping Cost</th>
                                    <td>$ {{ order_obj.shipping_total }}</td>
                                </tr>
                                <tr>
                                    <th>Total</th>
                                    <td>$ {{ order_obj.order_total }}</td>
                                </tr>
                            </tbody>
                        </table> 
                        </div>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Pay Now</button>
                            </form>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
		</div>
    </div>
    
	{% include "home/before-footer.html" %}	
	{% include "home/footer.html" %}	
    {% block js %}
    <script>

            var paymentForm = $(".payment-form");
            
            if(paymentForm.length > 1) {
                alert("Only one payment method allowed")
            }
            
            else if(paymentForm.length == 1){
            
                var pubKey = paymentForm.attr("data-token");
                var nextURL = paymentForm.attr("data-next-url");
                // Create a Stripe client.
                var stripe = Stripe(pubKey);
            
                // Create an instance of Elements.
                var elements = stripe.elements();
            
                // Custom styling can be passed to options when creating an Element.
                // (Note that this demo uses a wider set of styles than the guide below.)
                var style = {
                base: {
                    color: '#32325d',
                    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                    fontSmoothing: 'antialiased',
                    fontSize: '16px',
                    '::placeholder': {
                    color: '#aab7c4'
                    }
                },
                invalid: {
                    color: '#fa755a',
                    iconColor: '#fa755a'
                }
                };
            
                // Create an instance of the card Element.
                var card = elements.create('card', {style: style});
            
                // Add an instance of the card Element into the `card-element` <div>.
                card.mount('#card-element');
            
                // Handle real-time validation errors from the card Element.
                card.addEventListener('change', function(event) {
                var displayError = document.getElementById('card-errors');
                if (event.error) {
                    displayError.textContent = event.error.message;
                } else {
                    displayError.textContent = '';
                }
                });
            
                // Handle form submission.
                var form = document.getElementById('payment-form');
                form.addEventListener('submit', function(event) {
                event.preventDefault();
            
                stripe.createToken(card).then(function(result) {
                    if (result.error) {
                    // Inform the user if there was an error.
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                    } else {
                    // Send the token to your server.
                    stripeTokenHandler(nextURL,result.token);
                    }
                });
                });
            
                function redirectToNext(nextPath,timeoffset){
                    if (nextPath){
                        setTimeout(function(){
                            window.location.href = nextPath;
                        },timeoffset)
                    }
                }
                // Submit the form with the token ID.
                function stripeTokenHandler(nextURL,token) {
                    var paymentMethodEndPoint = "/billing/payment/add-card/"
                    var data = {
                        "token":token.id
                    }
                    $.ajax({
                        data: data,
                        url: paymentMethodEndPoint,
                        method: "POST",
                        success: function(data){
                            var seccessMgs = data.message || "Success! Your card has been added."
                            card.clear()
                            if (nextURL){
                                seccessMgs = seccessMgs + "<br><i class='fas fa-spin fa-spinner'></i> Redirecting..."
                            }
                            if ($.alert){
                                $.alert(seccessMgs)
                                redirectToNext(nextURL,1500)
                            } else {
                                $.alert(seccessMgs)
                            }
                            
                            redirectToNext(nextURL,1500)
                        }
                    })
                }
            
            }
</script>
    {% endblock %}
</html>

src/templates/cart/home.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Cart | E-BUY</title>
	{% include "home/header.html" %}
</head>

<body>

	{% include "home/nav-others.html" %}
	<!-- //navigation -->
	<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<!-- page -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="{% url "home:homepage" %}">Home</a>
						<i>|</i>
					</li>
					<li>Checkout</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- //page -->
	<!-- checkout page -->
	<div class="privacy">
		<div class="container">
			<!-- tittle heading -->
			<h3 class="tittle-w3l">Checkout
				<span class="heading-style">
					<i></i>
					<i></i>
					<i></i>
				</span>
            </h3>
            
			<!-- //tittle heading -->
			<div class="checkout-right">
				<div class="table-responsive">
                    {% if cart_obj.product.exists %}
                    <table class="table table-bordered cart-table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Product Name</th>
                                    <th scope="col">Product Price</th>
                                 </tr>
                            </thead>
                            <tbody class = "cart-body">
                                    {% for obj in cart_obj.product.all %}
                                    <tr class="cart-product">
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>
                                            <a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a>
                                            <small>
                                                {% include "cart/snippets/remove-product.html" with product_id=obj.id %}
                                            </small>
                                            </td>
                                        <td>$ {{ obj.price }}</td>
                                    </tr>
                                    {% endfor %}
                                <tr>
                                    <td colspan="2"></td>
                                    <td><b>Sub Total</b> <span class="cart-subtotal">$ {{ cart_obj.sub_total }}</span></td>
                                </tr>
                                <tr>
                                    <td colspan="2"></td>
                                    <td><b>Total</b> <span class="cart-total">$ {{ cart_obj.total }}</span></td>
                                </tr>
                                <tr>
                                    <td colspan="2"></td>
                                    <td><a href="{% url "cart:checkout" %}" class="btn btn-block btn-primary">Checkout</a></td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="cart-item-remove-form" style="display: none;">
                            {% include "cart/snippets/remove-product.html" %}
                        </div>
                    {% else%}
                        <h4>Cart is empty</h4>
                    {% endif %}
				</div>
            </div>
		</div>
	</div>
	{% include "home/before-footer.html" %}	
	{% include "home/footer.html" %}	

</html>