src/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
                    login_views,
                    register_user,
                    guest_login_views
                )

app_name = "accounts"
urlpatterns = [
    path('login/', login_views,name="login"),
    path('guest-login/', guest_login_views,name="guest-login"),
    path('logout/', LogoutView.as_view(),name="logout"),
    path('register/', register_user,name="register"),
]

src/cart/urls.py
from django.urls import path
from  .views import (
                    cart_home,
                    cart_update,
                    checkout_home,
                    checkout_done,
                    cart_update_api_view
                )

app_name = "cart"

urlpatterns = [
    path('', cart_home,name="cart-home"),
    path('update/', cart_update,name="cart-update"),
    path('checkout/', checkout_home,name="checkout"),
    path('checkout/success/', checkout_done,name="checkout-success"),
    path('api/', cart_update_api_view,name="cart-update-api"),
]

src/eCommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include("products.urls")),
    path('search/', include("search.urls")),
    path('cart/', include("cart.urls")),
    path('accounts/', include("accounts.urls")),
    path('address/', include("address.urls")),
    path('billing/', include("billing.urls")),
    path('', include("home.urls")),

]


if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/home/urls.py
from django.urls import path
from .views import (
                home_page
            )


app_name = "home"
urlpatterns = [

    path('',home_page,name="homepage")

]

src/products/urls.py
from django.urls import path
from .views import (
                ProductList,
                ProductDetail,
                FeaturedProductListView,
                CategoryDetail
            )

app_name = "products"

urlpatterns = [

    # product list
    path('list/', ProductList.as_view(),name="product-list"),
    # featured product list
    path('featured/list/', FeaturedProductListView.as_view(),name="featured-product-list"),
    # product detail
    path('<slug:slug>/detail/', ProductDetail.as_view(),name="product-detail"),
    path('category/<slug:slug>/detail/', CategoryDetail.as_view(),name="category-detail"),
]

src/search/urls.py
from django.urls import path
from .views import (
                SearchProductView
            )

app_name = "search"

urlpatterns = [

    # product list
    path('', SearchProductView.as_view(),name="product-search"),

]

src/home/models.py
from django.db import models

# Create your models here.

src/home/views.py
from django.shortcuts import render
from products.models import (
                        Product,
                        ProductCategory
                    )
from cart.models import Cart

def home_page(request):

    # get latest arival product
    new_products = Product.objects.latest_arival()

    # get featured product 
    featured_product = Product.objects.featured()

    # get mens collections
    mens_collection = Product.objects.mens_collection()

    # get mens collections
    womens_collection = Product.objects.womens_collection()

    # get offer
    special_offer = Product.objects.special_offer()

    # get special deal
    special_deal = Product.objects.special_deal()

    # get cart object
    cart_obj,new_obj = Cart.objects.create_or_get(request)

    # get category
    category = ProductCategory.objects.all()


    template_name = "home/index.html"
    
    context = {
        "new_products":new_products,
        "featured_product":featured_product,
        "cart_obj":cart_obj,
        "mens_collection":mens_collection,
        "special_offer":special_offer,
        "womens_collection":womens_collection,
        "special_deal":special_deal,
        "all_category":category,
        "category_count":category.count()
    }

    return render(request,template_name,context)

src/templates/home/footer.html
    {% load static %}
    <!-- js-files -->
    <!-- jquery -->
    <script src="{% static "index/js/jquery-2.1.4.min.js" %}"></script>
	
	<!-- //jquery -->

    <!-- jquery-confirm JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

	<!-- popup modal (for signin & signup)-->
	<script src="{% static "index/js/jquery.magnific-popup.js" %}"></script>
	<script>
		$(document).ready(function () {
			$('.popup-with-zoom-anim').magnificPopup({
				type: 'inline',
				fixedContentPos: false,
				fixedBgPos: true,
				overflowY: 'auto',
				closeBtnInside: true,
				preloader: false,
				midClick: true,
				removalDelay: 300,
				mainClass: 'my-mfp-zoom-in'
			});

		});
</script>
    
	
	<!-- cart-js -->
	<script src="{% static "index/js/minicart.js" %}"></script>
	<script>
		paypalm.minicartk.render(); //use only unique class names other than paypalm.minicartk.Also Replace same class name in css and minicart.min.js

		paypalm.minicartk.cart.on('checkout', function (evt) {
			var items = this.items(),
				len = items.length,
				total = 0,
				i;

			// Count the number of each item in the cart
			for (i = 0; i < len; i++) {
				total += items[i].get('quantity');
			}

			if (total < 3) {
				alert('The minimum order quantity is 3. Please add more to your shopping cart before checking out');
				evt.preventDefault();
			}
		});
</script>
	<!-- //cart-js -->

	<!-- price range (top products) -->
	<script src="{% static "index/js/jquery-ui.js" %}"></script>
	<script>
		//<![CDATA[ 
		$(window).load(function () {
			$("#slider-range").slider({
				range: true,
				min: 0,
				max: 9000,
				values: [50, 6000],
				slide: function (event, ui) {
					$("#amount").val("$" + ui.values[0] + " - $" + ui.values[1]);
				}
			});
			$("#amount").val("$" + $("#slider-range").slider("values", 0) + " - $" + $("#slider-range").slider("values", 1));

		}); //]]>
</script>
	<!-- //price range (top products) -->

	<!-- flexisel (for special offers) -->
	<script src="{% static "index/js/jquery.flexisel.js" %}"></script>
	<script>
		$(window).load(function () {
			$("#flexiselDemo1").flexisel({
				visibleItems: 3,
				animationSpeed: 1000,
				autoPlay: true,
				autoPlaySpeed: 3000,
				pauseOnHover: true,
				enableResponsiveBreakpoints: true,
				responsiveBreakpoints: {
					portrait: {
						changePoint: 480,
						visibleItems: 1
					},
					landscape: {
						changePoint: 640,
						visibleItems: 2
					},
					tablet: {
						changePoint: 768,
						visibleItems: 2
					}
				}
			});

		});
</script>
	<!-- //flexisel (for special offers) -->

	<!-- password-script -->
	<script>
		window.onload = function () {
			document.getElementById("password1").onchange = validatePassword;
			document.getElementById("password2").onchange = validatePassword;
		}

		function validatePassword() {
			var pass2 = document.getElementById("password2").value;
			var pass1 = document.getElementById("password1").value;
			if (pass1 != pass2)
				document.getElementById("password2").setCustomValidity("Passwords Don't Match");
			else
				document.getElementById("password2").setCustomValidity('');
			//empty string means no validation error
		}
</script>
	<!-- //password-script -->

	<!-- smoothscroll -->
	<script src="{% static "index/js/SmoothScroll.min.js" %}"></script>
	<!-- //smoothscroll -->

	<!-- start-smooth-scrolling -->
	<script src="{% static "index/js/move-top.js" %}"></script>
	<script src="{% static "index/js/easing.js" %}"></script>
	<script>
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();

				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 1000);
			});
		});
</script>
	<!-- //end-smooth-scrolling -->

	<!-- smooth-scrolling-of-move-up -->
	<script>
		$(document).ready(function () {
			/*
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
			};
			*/
			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
</script>
	<!-- //smooth-scrolling-of-move-up -->

	<!-- for bootstrap working -->
	<script src="{% static "index/js/bootstrap.js" %}"></script>
	<!-- //for bootstrap working -->
	<!-- //js-files -->

     <!-- Django Secure AJAX JS -->
     <script src="{% static "js/csrf.ajax.js" %}"></script>

     <!-- eCommerce Custom JS -->
     <script src="{% static "js/ecommerce.js" %}"></script>
     
     <!-- Stripe JS -->
     <script src="https://js.stripe.com/v3/"></script>
 
     {% block js %}{% endblock %}

src/templates/home/header.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="{% static "index/css/bootstrap.css" %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static "index/css/style.css" %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static "index/css/popuo-box.css" %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" type="text/css" href="{% static "index/css/jquery-ui1.css" %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">

src/templates/home/index.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>E-BUY</title>
	{% include "home/header.html" %}
</head>

<body>
	{% include "home/nav-others.html" %}
	<!-- banner -->
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators-->
		<ol class="carousel-indicators">
			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			<li data-target="#myCarousel" data-slide-to="1" class=""></li>
			<li data-target="#myCarousel" data-slide-to="2" class=""></li>
			<li data-target="#myCarousel" data-slide-to="3" class=""></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<div class="container">
					<div class="carousel-caption">
						<h3>Big
							<span>Save</span>
						</h3>
						<p>Get flat
							<span>10%</span> Cashback</p>
						<a class="button2" href="{% url "products:product-list" %}">Shop Now </a>
					</div>
				</div>
			</div>
			<div class="item item2">
				<div class="container">
					<div class="carousel-caption">
						<h3>Healthy
							<span>Saving</span>
						</h3>
						<p>Get Upto
							<span>30%</span> Off</p>
						<a class="button2" href="{% url "products:product-list" %}">Shop Now </a>
					</div>
				</div>
			</div>
			<div class="item item3">
				<div class="container">
					<div class="carousel-caption">
						<h3>Big
							<span>Deal</span>
						</h3>
						<p>Get Best Offer Upto
							<span>20%</span>
						</p>
						<a class="button2" href="{% url "products:product-list" %}">Shop Now </a>
					</div>
				</div>
			</div>
			<div class="item item4">
				<div class="container">
					<div class="carousel-caption">
						<h3>Today
							<span>Discount</span>
						</h3>
						<p>Get Now
							<span>40%</span> Discount</p>
						<a class="button2" href="{% url "products:product-list" %}">Shop Now </a>
					</div>
				</div>
			</div>
		</div>
		<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
	<!-- //banner -->

	<!-- top Products -->
	<div class="ads-grid">
		<div class="container">
			<!-- tittle heading -->
			<h3 class="tittle-w3l">Our Top Products
				<span class="heading-style">
					<i></i>
					<i></i>
					<i></i>
				</span>
			</h3>
			<!-- //tittle heading -->
			<!-- product left -->
			<div class="side-bar col-md-3">
			
				<!-- //price range -->
				<!-- food preference -->
				<div class="left-side">
					<h3 class="agileits-sear-head">Category</h3>
					<ul class="list-group">
						{% for category in all_category %}
							<li class="list-group-item d-flex justify-content-between align-items-center">
							  	<a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
							  	<span class="badge badge-warning badge-pill">{{ category|count_product }}</span>
							</li>
						{% endfor %}
					</ul>
				</div>
				<!-- //food preference -->
			
				<!-- //cuisine -->
				<!-- deals -->
				<div class="deal-leftmk left-side">
					<h3 class="agileits-sear-head">Special Deals</h3>
					{% for products in special_deal %}
					<div class="special-sec1">
						{% if products.product_image %} 
							<div class="col-xs-4 img-deals">
								<img src="{{ products.product_image.url }}" alt="{{ products.title }}" class="img-responsive">
							</div>
						{% endif %}
						<div class="col-xs-8 img-deal1">
							<h3>{{ products.title }}</h3>
							<a href="{{ products.get_absolute_url }}">$ {{ products.price }}</a>
							{% include "products/snippets/update-cart.html" with product=products cart=cart_obj %}
						</div>
						<div class="clearfix"></div>
					</div>
					{% endfor %}
				</div>
				<!-- //deals -->
			</div>
			<!-- //product left -->
			<!-- product right -->
			<div class="agileinfo-ads-display col-md-9">
				<div class="wrapper">
					<!-- first section (nuts) -->
					<div class="product-sec1">
                        <h3 class="heading-tittle">Latest</h3>
                        {% for products in new_products %}
						<div class="col-md-4 product-men">
							<div class="men-pro-item simpleCart_shelfItem">
								<div class="men-thumb-item">
                                    {% if products.product_image %} 
                                        <img src="{{ products.product_image.url }}" alt="{{ products.title }}" class="img-responsive">
                                    {% endif %}
									<div class="men-cart-pro">
										<div class="inner-men-cart-pro">
											<a href="{{ products.get_absolute_url }}" class="link-product-add-cart">Quick View</a>
										</div>
									</div>
									<span class="product-new-top">New</span>
								</div>
								<div class="item-info-product ">
									<h4>
										<a href="{{ products.get_absolute_url }}">{{ products.title }}</a>
									</h4>
									<div class="info-product-price">
										<span class="item_price">$ {{ products.price }}</span>
										<del>$ {{ products.price|multiply:.47 }} </del>
									</div>
									<div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                                        {% include "products/snippets/update-cart.html" with product=products cart=cart_obj %}
									</div>

								</div>
							</div>
						</div>
                        {% endfor %}
                        <div class="clearfix"></div>
					</div>
					<!-- //first section (nuts) -->
					<!-- second section (nuts special) -->
					<div class="product-sec1 product-sec2">
						<div class="col-xs-7 effect-bg">
							<h3 class="">Pure Energy</h3>
							<h6>Enjoy our all healthy Products</h6>
							<p>Get Extra 10% Off</p>
						</div>
						<h3 class="w3l-nut-middle">Nuts & Dry Fruits</h3>
						<div class="col-xs-5 bg-right-nut">
							<img src="{% static "index/images/nut1.png" %}" alt="">
						</div>
						<div class="clearfix"></div>
                    </div>
				</div>
					<!-- //second section (nuts special) -->
					<!-- third section (oils) -->
					<div class="product-sec1">
                        <h3 class="heading-tittle">Featured Products</h3>
                        {% for products in featured_product %}
						<div class="col-md-4 product-men">
							<div class="men-pro-item simpleCart_shelfItem">
								<div class="men-thumb-item">
                                    {% if products.product_image %} 
                                        <img src="{{ products.product_image.url }}" alt="{{ products.title }}" class="img-responsive">
                                    {% endif %}
									<div class="men-cart-pro">
										<div class="inner-men-cart-pro">
											<a href="{{ products.get_absolute_url }}" class="link-product-add-cart">Quick View</a>
										</div>
									</div>
									<span class="product-new-top">New</span>
								</div>
								<div class="item-info-product ">
									<h4>
										<a href="{{ products.get_absolute_url }}">{{ products.title }}</a>
									</h4>
									<div class="info-product-price">
										<span class="item_price">$ {{ products.price }}</span>
										<del>$ {{ products.price|multiply:.47 }}</del>
									</div>
									<div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                                        {% include "products/snippets/update-cart.html" with product=products cart=cart_obj %}
									</div>

								</div>
							</div>
                        </div>
                        {% endfor %}
                        <div class="clearfix"></div>
                    </div>
					<!-- //third section (oils) -->
					<!-- fourth section (noodles) -->
					<div class="product-sec1">
						<h3 class="heading-tittle">Men's Fashion</h3>
						{% for products in mens_collection %}
						<div class="col-md-4 product-men">
							<div class="men-pro-item simpleCart_shelfItem">
								<div class="men-thumb-item">
                                    {% if products.product_image %} 
                                        <img src="{{ products.product_image.url }}" alt="{{ products.title }}" class="img-responsive">
                                    {% endif %}
									<div class="men-cart-pro">
										<div class="inner-men-cart-pro">
											<a href="{{ products.get_absolute_url }}" class="link-product-add-cart">Quick View</a>
										</div>
									</div>
									<span class="product-new-top">New</span>
								</div>
								<div class="item-info-product ">
									<h4>
										<a href="{{ products.get_absolute_url }}">{{ products.title }}</a>
									</h4>
									<div class="info-product-price">
										<span class="item_price">$ {{ products.price }}</span>
										<del>$ {{ products.price|multiply:.47 }}</del>
									</div>
									<div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                                        {% include "products/snippets/update-cart.html" with product=products cart=cart_obj %}
									</div>

								</div>
							</div>
                        </div>
                        {% endfor %}
						<div class="clearfix"></div>
					</div>
					<!-- //fourth section (noodles) -->
				</div>
			</div>
			<!-- //product right -->
		</div>
	</div>
    <!-- //top products -->
    
	<!-- special offers -->
	<div class="featured-section" id="projects">
		<div class="container">
			<!-- tittle heading -->
			<h3 class="tittle-w3l">Special Offers
				<span class="heading-style">
					<i></i>
					<i></i>
					<i></i>
				</span>
			</h3>
			<!-- //tittle heading -->
			<div class="content-bottom-in">
				<ul id="flexiselDemo1">
                    {% for products in special_offer %}
					<li>
						<div class="w3l-specilamk">
							<div class="speioffer-agile">
                                {% if products.product_image %}
								<a href="{{ products.get_absolute_url }}">
                                    <img src="{{ products.product_image.url }}" alt="{{ products.title }}" class="img-responsive">
                                </a>
                                {% endif %}
							</div>
							<div class="product-name-w3l">
								<h4>
									<a href="{{ products.get_absolute_url }}">{{ products.title }}</a>
								</h4>
								<div class="w3l-pricehkj">
									<h6>$ {{ products.price }}</h6>
									<p>Save 86% <del>$ {{ products.price|multiply:.86 }}</del></p>
								</div>
								<div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                                    <a href="{{ products.get_absolute_url }}"><input type="submit" name="submit" value="view product" class="button" /></a>
								</div>
							</div>
						</div>
                    </li>
                    {% endfor %}
                </ul>
			</div>
        </div>
    </div>
    
    <div class="product-sec1">
            <h3 class="heading-tittle">Women's Fashion</h3>
            {% for products in womens_collection %}
            <div class="col-md-3 product-men">
                <div class="men-pro-item simpleCart_shelfItem">
                    <div class="men-thumb-item">
                        {% if products.product_image %} 
                            <img src="{{ products.product_image.url }}" alt="{{ products.title }}" class="img-responsive">
                        {% endif %}
                        <div class="men-cart-pro">
                            <div class="inner-men-cart-pro">
                                <a href="{{ products.get_absolute_url }}" class="link-product-add-cart">Quick View</a>
                            </div>
                        </div>
                        <span class="product-new-top">47 % OFF</span>
                    </div>
                    <div class="item-info-product ">
                        <h4>
                            <a href="{{ products.get_absolute_url }}">{{ products.title }}</a>
                        </h4>
                        <div class="info-product-price">
                            <span class="item_price">$ {{ products.price }}</span>
                            <del>$ {{ products.price|multiply:.47 }}</del>
                        </div>
                        <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                            {% include "products/snippets/update-cart.html" with product=products cart=cart_obj %}
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="clearfix"></div>
        </div>
        
	<!-- //special offers -->
	{% include "home/before-footer.html" %}	
	{% include "home/footer.html" %}	
</html>

src/templates/home/nav-others.html
{% load static %}
<!-- //top-header -->
<!-- header-bot-->
<div class="header-bot">
    <div class="header-bot_inner_wthreeinfo_header_mid">
        <!-- header-bot-->
        <div class="col-md-4 logo_agile">
            <h1>
                <a href="{% url "home:homepage" %}">
                    <img src="{% static "images/logo.png" %}" alt=" ">
                </a>
            </h1>
        </div>
        <!-- header-bot -->
        <div class="col-md-8 header">
            <!-- header lists -->
            <ul>
                <li>
                    <a href="#" data-toggle="modal" data-target="#myModal1">
                        <span class="fas fa-truck" aria-hidden="true"></span>Track Order</a>
                </li>
                <li>
                    <span class="fas fa-phone" aria-hidden="true"></span> 001 234 5678
                </li>
                {% if not request.user.is_authenticated %}
                <li>
                    <a href="{% url "accounts:login" %}">
                        <span class="fas fa-unlock-alt" aria-hidden="true"></span> Sign In </a>
                </li>
                <li>
                    <a href="{% url "accounts:register" %}">
                        <span class="fas fa-pencil-square-o" aria-hidden="true"></span> Sign Up </a>
                </li>
                {% else %}
                <li>
                    <span class="fas fa-user" aria-hidden="true"></span> Welcome , {{ request.user }}
                </li>
                <li> 
                    <a href="{% url "accounts:logout" %}">
                    <span class="fas fa-unlock-alt" aria-hidden="true"></span> Sign Out </a>
                </li>
               
                {% endif %}
            </ul>
            <!-- //header lists -->
            <!-- search -->
            <div class="agileits_search">
                <form class="form-inline my-2 my-lg-0 search-form" action="{% url "search:product-search" %}">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search your products here ...." aria-label="Search" name="q">
                    <button class="btn btn-success" type="submit" style="margin-top: 10px;"> <span class="fa fa-search" aria-hidden="true"> </span> Search</button>
                </form>
            </div>
            <!-- //search -->
            <!-- cart details -->
            <div class="top_nav_right">
                <div class="wthreecartaits wthreecartaits2 cart cart box_1">
                    <a class="btn btn-danger w3view-cart" href="{% url "cart:cart-home" %}"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i> <span class="cart-count"> {{ request.session.cart_total }}</span> Items</a>
                </div>
            </div>
            <!-- //cart details -->
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>


<!-- navigation -->
<div class="ban-top">
    <div class="container">
        <div class="top_nav_left">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                            aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav menu__list">
                            <li class="active">
                                <a class="nav-stylehead" href="{% url "home:homepage" %}">Home
                                </a>
                            </li>
                            <li>
                                <a class="nav-stylehead" href="{% url "products:product-list" %}">All Products</a>
                            </li>
                            <li>
                                <a class="nav-stylehead" href="{% url "products:featured-product-list" %}">Featured Products</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- //navigation -->